WeAreBrian/project-fox-poc

Assets/Scenes/ChainTest.unity, Assets/Scripts/AnchorHolder.cs, Assets/Scripts/VerticalMovement.cs
https://www.notion.so/Limit-Jump-height-while-carrying-anchor-6b5de02bb37f4e67bb0a6f34f24f57e7?pvs=4 
Added weight to the fox while holding the anchor
=> Poc 07 anchor weight

Assets/Materials.meta, Assets/Materials/New Material.mat, Assets/Materials/New Material.mat.meta, Assets/Prefabs/Anchor.prefab, Assets/Prefabs/PlayerFox.prefab, Assets/Prefabs/Springboard.prefab, Assets/Prefabs/Springboard.prefab.meta, Assets/Scenes/SpringboardTest.unity, Assets/Scenes/SpringboardTest.unity.meta, Assets/Scripts/Anchor.cs, Assets/Scripts/Springboard.cs, Assets/Scripts/Springboard.cs.meta, ProjectSettings/TagManager.asset
- Added springboard script
- Created springboard prefab
- Created sprintboard test scene
- added interpolation to fox's rigidbody
- lowered mass and freezing constraints from anchor
- created terrain layer to prevent springboard from colliding with the ground
- pulled new changes to ensure it worked with grapple surfaces
=> Poc 15 create springboard

Assets/Scripts/MouseDirectionFromPlayerProcessor.cs
- Fixed mouse aim not working in builds
=> POC 98 Mouse aim doesn't work properly in builds

Assets/Prefabs/Anchor.prefab, Assets/Prefabs/AnchorChain.prefab, Assets/Prefabs/Platform.prefab, Assets/Prefabs/Platform.prefab.meta, Assets/Prefabs/PlayerFox.prefab, Assets/Prefabs/Springboard.prefab, Assets/Scenes/Levels.meta, Assets/Scenes/Levels/A.unity, Assets/Scenes/Levels/A.unity.meta, Assets/Scenes/Levels/Level Template.unity, Assets/Scenes/Levels/Level Template.unity.meta, Assets/Scripts/Anchor.cs, Assets/Scripts/AnchorHolder.cs, Assets/Scripts/ChainMovement.cs, Assets/Scripts/Springboard.cs, Assets/Scripts/WorldInteract.cs, ProjectSettings/Physics2DSettings.asset, ProjectSettings/TimelineSettings.asset
=> Bug Fixes and Tweaks (POC 67,89,102,104)

Assets/Materials/New Material 1.mat, Assets/Materials/New Material 1.mat.meta, Assets/Prefabs/GrappleSurface.prefab, Assets/Prefabs/GrappleSurface.prefab.meta
=> Poc 94 grapple surface

Assets/Prefabs/PlayerFox.prefab, Assets/Scenes/Levels/A.unity, Assets/Scripts/HorizontalMovement.cs
=> Poc 103 input velocity cap

Assets/Prefabs/TeleporterForTesting.prefab, Assets/Prefabs/TeleporterForTesting.prefab.meta, Assets/Scenes/Playground.unity, Assets/Scenes/Playground.unity.meta, Assets/Scripts/Teleporter.cs, Assets/Scripts/Teleporter.cs.meta
- Added playground scene
- Added teleporter scripts/prefabs (was not needed but I felt is super useful for testing playground, press 1 or 2 to use)(can also be used in other levels easily by just dragging and dropping the prefabs into the level)(and ye I could've used a second script to manage all the teleporters but I wanted to try make it to be self contained)
=> Poc 19 playground

Assets/Prefabs/AnchorChain.prefab, Assets/Prefabs/PlayerFox.prefab, Assets/Scenes/Levels/A.unity, Assets/Scripts/Anchor.cs, Assets/Scripts/AnchorHolder.cs, Assets/Scripts/AnchorStall.cs, Assets/Scripts/Chain.cs, Assets/Scripts/ChainMovement.cs, Assets/Scripts/Tug.cs, Assets/Scripts/VerticalMovement.cs, Assets/player.physicsMaterial2D, Assets/player.physicsMaterial2D.meta
- player is propelled towards anchor or closest cinch when tug action is taken
- player picks up anchor automatically within x seconds of tug action
- tug action pulls anchor under specified conditions
=> POC 26 Tugging Part 1 & 2

Assets/Prefabs/PlayerFox.prefab, Assets/Scenes/Levels/A.unity, Assets/Scripts/VerticalMovement.cs
- Link to ticket: https://www.notion.so/Feature-Coyote-Time-c046a9b21f204d5b818cfbeaa1ee01cb?pvs=4
- Added coyote time when player is not grounded
=> POC-71: Coyote Time

Assets/Scripts/VerticalMovement.cs
- Link to ticket: https://www.notion.so/Refactor-Vertical-Movement-1d3c290ab6d9438d8604c7dceef1c4c1?pvs=4
- Refactored jump code to have jump checks for better handling, and to prepare for jump buffer and variable jump height implementation
- Converted indents from spaces to tabs
- Right now if you press "jump" while mid-air, when the fox lands it will automatically jump again. This is a known cause from the refactor. It will be addressed with the jump buffer implementation. Because this refactor contains a lot of breaking changes, it needs to go out first so that other devs can continue working on their tickets
=> POC-145: VerticalMovement Refactor

Assets/Scenes/Levels/A.unity, Assets/Scripts/VerticalMovement.cs
- Link to ticket: https://www.notion.so/Feature-Jump-Buffering-82df8036a7f94926ae57ca7ce53a9d42?pvs=4
- Added jump buffer to be nice to players with jump request timings
=> POC-72: Jump Buffer

Assets/Animations/3d animations.meta, Assets/Animations/3d animations/FOX_ANI_RUN.fbx.meta, Assets/Animations/3d animations/FOX_ANI_SPECIALDANCE.fbx.meta, Assets/Animations/3d animations/fox_t_pose.fbx.meta, Assets/Images/Jungle/Untitled-1_0000_short_grass.png.meta, Assets/Images/Jungle/Untitled-1_0001_med_grass.png.meta, Assets/Images/Jungle/Untitled-1_0002_tall_grass.png.meta, Assets/Images/Jungle/Untitled-1_0003_small_bush.png.meta, Assets/Images/Jungle/Untitled-1_0003_small_rock.png.meta, Assets/Images/Jungle/Untitled-1_0004_massive_boulder.png.meta, Assets/Images/Jungle/Untitled-1_0004_pointy_bush.png.meta, Assets/Images/Jungle/Untitled-1_0005_chocky_bush.png.meta
- add meta files to art
unity was not opened when assets were merged
=> Add meta files

Assets/Scripts/Chain.cs
https://www.notion.so/Bug-make-chain-have-min-length-a5a99afa45ea4ab1bd9e4983c1f3b778?pvs=4
changed the chain length so you can load it in from any height
=> Poc 117 chain length issue

Assets/Scripts/AnchorStall.cs, Assets/Scripts/HorizontalMovement.cs, Assets/Scripts/VerticalMovement.cs, pull_request_template.md
- Hidden variables that shouldn't be messed with
- Also reformatted relevant files to match [this format](https://www.notion.so/Writing-Unity-C-Code-8765b4b2e9c44b618d47ee37afdd319a?pvs=4)
- Also included ticket link in PR template
=> POC-148: Hide unnecessary variables

Assets/Prefabs/Coin.prefab, Assets/Prefabs/Coin.prefab.meta, Assets/Scripts/Collectable.cs, Assets/Scripts/Collectable.cs.meta
https://www.notion.so/Basic-Collectable-007f88dc2dbd49e0ac3f86d5c3902361?pvs=4
=> POC-183-Basic-Collectable

Assets/Prefabs/Anchor.prefab
**Test scene (if any): Any scene**
- moved and scaled anchor collider to fit the model
=> 189 Anchor Collider

Assets/Scripts/AnimatorStateMachine.cs
Any scene with the fox.
Uses a range for detecting input values.
=> Fix (Animator Script): now accounts for controller

Assets/InputActions/Player.inputactions, Assets/Scenes/Template/Stage Template.unity, Assets/Scripts/Anchor.cs, Assets/Scripts/ChainClimber.cs
- Level 1/Any stage
- Fixed climbing input
- Fixed anchor collision checking
- Fixed camera in template scene
=> FOX-75: Fix chain climb

Assets/Prefabs/PlayerFox.prefab, Assets/Scenes/Levels to port/Level 1/Stage 3.unity, Assets/Scripts/AnchorThrower.cs
- Added arrow to fox prefab
- Added code to aim arrow when winding up anchor throw
- added toggle for switching between arrow and trajectory line
=> Fox 106 Aim Indicator (Arrow)

Assets/Prefabs/PlayerFox.prefab, Assets/Scenes/Levels to port/Level 1/Stage 3.unity, Assets/Scripts/AnchorThrower.cs, Assets/Scripts/Grounded.cs, Assets/Scripts/HorizontalMovement.cs, Assets/Scripts/VerticalMovement.cs
- added landed event to grounded to trigger on frame of landing
- added jumped event to vertical movement to trigger on frame of successful jump
- added bhop, which tracks previous air speed and returns it to fox if jump is pressed shortly after landing
- added bullet time to anchor throw windup while not grounded
- changed horizontal velocity reset to setting movespeed to 0 when winding up anchor throw. this is so momentum is kept while winding up in the air
=> Fox 107 Momentum Changes

Assets/Scripts/AnchorThrower.cs, Assets/Scripts/ChainAttachment.cs, Assets/Scripts/ChainClimber.cs, Assets/Scripts/ChainMovement.cs, Assets/Scripts/HorizontalMovement.cs, Assets/Scripts/IdealChain.cs, Assets/Scripts/PhysicsChain.cs, Assets/Scripts/Recall.cs, Assets/Scripts/Switch.cs
FOX-109-Fix-Event-Subscriptions
fixed all the event subscriptions that weren't unsubscribing ondisable()
=> FOX-109-Fix-Event-Subscriptions

.github/workflows/build.yml
- Changed version to auto for webgl as well
=> FOX-117: Amend

.github/release-drafter.yml, .github/workflows/build.yml, .github/workflows/release.yml
- Cleaned up build pipeline + some annotations
- Added release pipeline (can only be manually activated)
~~- [ ] I have run the game locally~~
~~- [ ] I have performed self-review on my code~~
~~- [ ] I have confirmed critical features still function~~
=> FOX-121: Upgrade build pipeline

.github/workflows/build.yml, .github/workflows/release.yml
- Fixed build pipeline reference error
- Fixed release pipeline input context syntax error and also reference error
~~- [ ] I have run the game locally~~
~~- [ ] I have performed self-review on my code~~
~~- [ ] I have confirmed critical features still function~~
=> FOX-121 (amend): Fix reference error for Build and Release Pipeline

.github/workflows/build.yml, ProjectSettings/ProjectSettings.asset
- Changed webgl build settings
- Added credentials to webgl build
~~- [ ] I have run the game locally~~
~~- [ ] I have performed self-review on my code~~
~~- [ ] I have confirmed critical features still function~~
=> FOX-121 (amend): Fix webgl build error

Assets/Scripts/AnchorThrower.cs
nuf sed. anchor snaps to the aim arrow direction. not really much more to say than that. not gonna lie my friend.
=> FOX-136-Make-Anchor-Snap-To-Aim-Arrow

Assets/Prefabs/PlayerFox.prefab, Assets/Scripts/AnchorStall.cs, Assets/Scripts/ChainTugger.cs
=> FOX-132: removed tug and stall components

Assets/Animations/2d enviroment sprites/GrapplePlant.controller, Assets/Animations/2d enviroment sprites/GrapplePlant.controller.meta, Assets/Animations/2d enviroment sprites/OpenAndClose.anim, Assets/Animations/2d enviroment sprites/OpenAndClose.anim.meta, Assets/Animations/2d enviroment sprites/lilly sprites.png.meta, Assets/Prefabs/GrappleFlower.prefab, Assets/Prefabs/GrappleFlower.prefab.meta, Assets/Scenes/Test/Brians Level Idea.unity, Assets/Scripts/GrappleFlower.cs, Assets/Scripts/GrappleFlower.cs.meta
- `Scenes/Test/Brians Test Level.unity`
- created grapple flower
=> Fox 150 implement grapple flower

Assets/Scenes/Test/TemplateLevel.unity, Assets/Scenes/Test/TemplateLevel.unity.meta
=> FOX-86: fix

Assets/Scripts/UI/Timer/GameTimer.cs, Assets/Scripts/Utils.meta, Assets/Scripts/Utils/TimeFormatter.cs, Assets/Scripts/Utils/TimeFormatter.cs.meta
- `Scenes/Brians Level Idea.unity`
- Extract timer util function
=> FOX-218: Timer util function

Assets/BangBangBangEndState.cs, Assets/BangBangBangEndState.cs.meta, Assets/Scripts/BangBangBang.cs, Assets/UI/Bang Bang Bang/Animations/Bang Bang Bang Canvas.controller, Assets/UI/Bang Bang Bang/Animations/End.anim, Assets/UI/Bang Bang Bang/Animations/Fade Wipe.anim
- `Scenes/Intro Anim.unity`
- Updated BBB controller script to remove loadscene.
- Added end state script to load scene on final animation state.
- Updated End and Fade Wipe anims to include fade to black.
=> FOX-228-Update-Bang-Bang-Bang

Assets/Scenes/Test/TemplateLevel.unity
- `Scenes/test/levelTemplate.unity`
- added platform art
=> FOX-239: lvl template 

Assets/UI/Bang Bang Bang/Animations/Fade Wipe.anim
- `Assets/Scenes/Test/Intro Anim.unity`
- edited fade wipe animation so there is no more flash before load scene
=> FOX-240-Tweak-Bang-Bang-Bang-fade

Assets/Prefabs/PlayerFox.prefab, Assets/Scripts/HorizontalMovement.cs
- Any
- Added footsteps, sound effects to Fox Prefab..
- edited script to use list size instead of hard coded number.
=> FOX-272 foot steps sfx

Assets/Scenes/Test/Onboarding.unity
- `Assets/Scenes/Test/Onboarding.unity`
- fix missing platform assets
=> FOX-263 Fix missing assets in tutorial lvl

Assets/Prefabs/LevelEnd.prefab, Assets/Scenes/Template/TemplateLevel.unity
=> FOX-274 update level finish prefab image

Assets/Scenes/Test/other forest deco 2.unity
- `Assets/Scenes/Test/other forest deco 2.unity`
- updated springboard scale and positions
- changed some level features
- updated some level deco
=> FOX-280-Update-springboards-OFD-lvl

Assets/Scripts/Anchor.cs
-any
- fixed speed bug (the bug where recalling quickly caused the player to go nuts)
=> FOX-287-speed-bug

Assets/OToon- URP Toon Shading/Unity_2021_2022_upgrade.unitypackage.meta, Assets/Prefabs/LevelEnd.prefab, Assets/Scripts/LevelEnd.cs, Assets/Scripts/UI/CloseOrOpenCircle.cs, Assets/Scripts/VFX/GrowAndShrinkLevelEndGlow.cs, Assets/Scripts/VFX/GrowAndShrinkLevelEndGlow.cs.meta, Assets/Scripts/VFX/SpeedLineTrail.cs
- any level with a level end statue
- Added ✨sparkles✨ to the statue
- Added a glowing circling behind the statue that grows and shrinks
- added slomo when player touches the level end
- added both a shrink or a grow effect to the glowing circle when player touches the level end
=> FOX-250-Freeze-or-Slow-Time-on-Level-Finish

Assets/Scripts/VFX/SimpleParalax.cs
- Brians level idea
- fix(parallax): Fixed parallax being offset after scene reloads
=> FOX-293-Fix-A-Different-Parallax-Bug

Assets/Prefabs/PauseMenuUI.prefab, Assets/Scenes/Test/Brians Level Idea.unity, Assets/Scripts/UI/ShowPauseMenu.cs
=> FOX-302: bug fix

Assets/Scenes/Final levels/Level 1.unity
=> LEVEL 1  DECO FIX

Assets/Scenes/Final levels/Level 1.unity, Assets/Shaders/BushyNotRoot_Foliage.mat
- Level 1 (aka brians level idea)
- added plant wind to level 1 brians level idea
=> FOX-309-Plants-shader-on-level-1

Assets/Art/2DFinalGameAssets/Background1Layer/Untitled-2-copy-3_0011_Layer-4.png.meta, Assets/Art/2DFinalGameAssets/Background1Layer/Untitled-2-copy-3_0015_Layer-3.png.meta, Assets/Art/2DFinalGameAssets/Background1Layer/Untitled-2-copy-3_0016_Layer-1.png.meta, Assets/Scenes/Final levels/Level 3.unity, Assets/Shaders/TallGround_Foliage.mat, Assets/Shaders/TallGround_Foliage.mat.meta
- level 3
- added shaders to plants on level 3
=> FOX-312-add-plant-shaders-to-level-3

Assets/Scenes/Final levels/Level 0.unity, Assets/Shaders/HangingMedium_Foliage.mat
- level 0
- added plant shaders to level 0
=> FOX-316-Add-plant-shaders-to-level-0

Assets/Scenes/Final levels/Level 1.unity
- `Scenes/Final Levels/Level 1.unity`
- moved layers closer to stage on z axis
=> 307-Parallax-Bug

Assets/Art/2DFinalGameAssets/Background2Layer/Materials.meta, Assets/Art/2DFinalGameAssets/Background2Layer/Materials/BG2 floor 4.2.mat, Assets/Art/2DFinalGameAssets/Background2Layer/Materials/BG2 floor 4.2.mat.meta, Assets/Scenes/Final levels/Level 0.unity, Assets/Scenes/Final levels/Level 1.unity, Assets/Scenes/Final levels/Level 2.unity, Assets/Scenes/Final levels/Level 3.unity
- Backgrounds updated, mainly in level 0 and 2
=> FOX-326-Backgrounds

Assets/Scripts/Spike.cs
//"Make foxs red again-" - Trump
//"-on DEATH" - Jess
- //"Make foxs red again-" - Trump
//"-on DEATH" - Jess
=> FOX-341-Make-Foxs-Red-Again

Assets/Prefabs/PlayerFox.prefab, Assets/Scripts/Recall.cs
- level3 (the water level)
- Recall now resets when in the water
=> FOX-337-Anchor-Recall-Reset-while-in-water

Assets/Scenes/Final levels/Level 0.unity
=> Update Level 0.unity

Assets/Prefabs/UI/Speedrun Timer.meta, Assets/Prefabs/UI/Speedrun Timer/Timer Text.prefab, Assets/Prefabs/UI/Speedrun Timer/Timer Text.prefab.meta, Assets/Scripts/LevelEnd.cs, Assets/Scripts/Utils/SaveUtils.cs
- Fix timer so that it will run on speedrun scenes and count in the leaderboard
=> FOX-344: Fix timer

Assets/Art/2DFinalGameAssets/Background1Layer/GoldPillar.png.meta, Assets/Art/2DFinalGameAssets/Background1Layer/GoldSpike.png.meta, Assets/Art/2DFinalGameAssets/Background1Layer/GoldStatue1.png.meta, Assets/Scenes/Final levels/Level 0.unity, Assets/Scenes/Final levels/Level 1.unity, Assets/Scenes/Final levels/Level 2.unity, Assets/Scenes/Final levels/Level 3.unity
=> decoration
